### ISSUE TITLE
ToDo: Weitere Storage Implementationen

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/shoppingcart#2]
Das AddOn stellt einen CookieStore und SessionStore zur Verfügung. Der CookieStore überdauert einige Tage, der SessionStore eine Browser Session. Die Umsetzung weiterer Stores ist super einfach und dauert wenige Minuten

Man kann Redis, Memcached. MySQL oder PDO nutzen. Ich werde keine weiteren implementieren, bin jedoch für PRs offen. Diese sollten nicht im Vendor liegen, sondern als eigene Class.

- [x] MySQL Storage
- [X] Redis Storage
- [X] Memcached Storage
- [X] Memcache Storage

Die Storages könnte man dann auch ziemlich smart an eine User-ID binden, um z.B. einen Warenkorb überdauernd zu erstellen, welcher noch Monate danach mit den gewählten Artikleln befüllt sein kann. Außerdem könnte man mit einem MySQL Storage z.B. auch User anschreiben und hinweisen, dass der Warenkorb noch Artikel etc. enthält.

Ich würde mich über einen PR freuen, ansonsten gerne als bezahlter Auftrag.

**Comment by hirbod** [comment]
Hab jetzt doch weitere Storage umgesetzt. Fehlt nur noch MySQL.

**Comment by joachimdoerr** [comment]
SQL wäre interessant für übergreifende domains oder geht das auch mit einer der anderen Lösungen ?

**Comment by hirbod** [comment]
Also REDIS und Memcached sind thoretisch auch übergreifend nutzbar.
