### ISSUE TITLE
Stand?

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/shoppingcart#4]
Hey, ich hab das Addon gerade zufällig entdeckt und hab bei einem Shop nahezu das gleiche gebaut vor kurzem. Warum ist das Addon nicht im Installer? Wird es noch weiterentwickelt oder was ist der Plan?

**Comment by hirbod** [comment]
Ist er, schon ziemlich lange. Auch produktiv im Einsatz :)

**Comment by phoebusryan** [comment]
Mhh, stimmt - es ist drin... hab das immer total übersehen. Sorry!

**Comment by hirbod** [comment]
Zum Plan: das Addon hier stellt ja nur ein Warenkorb Framework bereit. Ich hatte immer gehofft, das jemand mit Omnipay dann auch noch ein Payment Addon baut und irgendjemand noch ein Produkt Addon (ggf. auf Basis von yForm). Joachim war an etwas dran, aber hat sich irgendwie aktuell nicht groß weiterentwickelt

**Comment by phoebusryan** [comment]
Das klingt sehr cool. Habe mir Omnipay gerade angeschaut - cooles Ding. Muss mich mal mit Joachim dies bzgl. unterhalten. :-)
