### ISSUE TITLE
working help

### ISSUE THREAD

**Issue by danielellm** [FriendsOfREDAXO/shoppingcart#5]
hallo,
ich brauche eine kurze einleitung im umgang mit dem addon.

ich habe das addon installiert und das demo modul eingebunden.
jetzt habe ich ein zweites modul erstellt und wollte die cart damit auf einer zweiten seite auslesen

`$cart = ShoppingCart::factory();
dump($cart->getId());
dump($cart);
dump($cart->getStore());
dump($cart->toArray());`

die cart Id ist die gleiche wie im demo modul aber es sind keine items enthalten.
was mache ich falsch?

**Comment by hirbod** [comment]
Wenn du auf der zweiten Seite erneut nur die factory() aufrufst, generierst du eine neue Warenkorbinstanz. Du musst die cartId als ersten Parameter übergeben.

Seite 1:
```php
$cart = ShoppingCart::factory();
$cartId = $cart->getId();
```

Seite 2:
```php
$cart = ShoppingCart::factory($cartId);
```

Die $cartId musst du dir dann in einer Session oder so speichern, damit du auf der nächsten Seite darauf zugreifen kannst.

Oder aber du gehst gleich von Anfang an folgenden Weg:

Seite 1:
```php
$cart = ShoppingCart::factory('meineTolleId');
```

Seite 2:
```php
$cart = ShoppingCart::factory('meineTolleId');
```

**Comment by hirbod** [comment]
Edit: ich hab meinen Code vergessen gehabt:
https://github.com/FriendsOfREDAXO/shoppingcart/blob/master/lib/ShoppingCart.php#L20

Eigentlich müsste dein Ansatz funktionieren, ggf. hast du Cookies nicht erlaubt?

**Comment by danielellm** [comment]
leider funktioniert es nicht..

meine cookies/session wird gespeichert
ich lasse mir die cart per print anzeigen
und die session

seite 1:
`CartCart Object([id:CartCart:private] => a0dtq9li85bhuo9lk8gma3ho02[items:CartCart:private] => Array([0] => ShoppingCartItem Object([data:CartCartItem:private] => Array ([quantity] => 1 [price] => 1200 [tax] => 200[name] => Macbook Pro[sku] => MBP8GB[options] => Array([ram] => 8 GB[ssd] => 256 GB)))[1] => ShoppingCartItem Object([data:CartCartItem:private] => Array([quantity] => 1[price] => 959.99[tax] => 200[name] => Macbook Pro[sku] => MBP8GB[meinkey] => is cool)))[store:CartCart:private] => CartStorageSessionStore Object())`

seite 2:
`CartCart Object([id:CartCart:private] => a0dtq9li85bhuo9lk8gma3ho02[items:CartCart:private] => Array()[store:CartCart:private] => CartStorageSessionStore Object())`

session:
`Array([a0dtq9li85bhuo9lk8gma3ho02] => a:2:{s:2:"id";s:26:"a0dtq9li85bhuo9lk8gma3ho02";s:5:"items";a:2:{i:0;a:2:{s:2:"id";s:40:"acfe0d7f617feb88676fc5119f6dec4d6be6b93a";s:4:"data";a:6:{s:8:"quantity";i:1;s:5:"price";d:1200;s:3:"tax";d:200;s:4:"name";s:11:"Macbook Pro";s:3:"sku";s:6:"MBP8GB";s:7:"options";a:2:{s:3:"ram";s:4:"8 GB";s:3:"ssd";s:6:"256 GB";}}}i:1;a:2:{s:2:"id";s:40:"c09aef8e5a5f765a4577f4594e4ae1b1490f4639";s:4:"data";a:6:{s:8:"quantity";i:1;s:5:"price";d:959.99000000000001;s:3:"tax";d:200;s:4:"name";s:11:"Macbook Pro";s:3:"sku";s:6:"MBP8GB";s:7:"meinkey";s:7:"is cool";}}}}[cartid] => a0dtq9li85bhuo9lk8gma3ho02)`


es sieht so aus als ob alles in der session gespeichert wird aber dan nicht mehr mit deiner addon ausgelesen wird..

ich habe es jetzt mit `$cart->restore();`
probiert und es funktioniert..
allerdings kommt es zu einer fehlermeldung wenn ich gleich auf seite 2 gehe (also die session ohne inhalt ist)..
